Aufgabe1_Registrierung/Models/Spieler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aufgabe1_Registrierung.Models
{
    public class Spieler
    {
        public Spieler()
        {
        }

        private string _vorname;
        private string _nachname;
        private string _email;
        private string _telefon;
        private string _jahrgang;


        public string vorname
        {
            get { return _vorname; }
            set { _vorname = value; }
        }

        public string nachname
        {
            get { return _nachname; }
            set { _nachname = value; }
        }

        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        public string telefon
        {
            get { return _telefon; }
            set { _telefon = value; }
        }

        public string jahrgang
        {
            get { return _jahrgang; }
            set { _jahrgang = value; }
        }

    }
}

Aufgabe1_Registrierung/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Aufgabe1_Registrierung.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Startseite()
        {
            return View();
        }
    }
}

Aufgabe1_Registrierung/Controllers/RegistrierungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Aufgabe1_Registrierung.Controllers
{
    public class RegistrierungController : Controller
    {
        public IActionResult LoadFormular()
        {
            return View();
        }
    }
}

Aufgabe1_Registrierung/Controllers/SpielerDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using Aufgabe1_Registrierung.Models;
using Microsoft.AspNetCore.Mvc;
using Aufgabe1_Registrierung;
using Aufgabe1_Registrierung.Data;


namespace Aufgabe1_Registrierung.Controllers
{
    public class SpielerDetailController : Controller
    {

        public IActionResult SeeSpieler(string Vorname, string Nachname, string Telefon, string Email, string Jahrgang)
        {
            Spieler newSpieler = new Spieler() { vorname = Vorname, email = Email, jahrgang = Jahrgang, nachname = Nachname, telefon = Telefon };


            SpielerRepo.SpielerListe.Add(newSpieler);

            return View(newSpieler);
        }

        //Folie 4-21 doch es geht noch einfacher
        // *************************************************************************************

        //public IActionResult SeeSpieler2()
        //{
        //    Spieler newSpieler = null;

        //    if (Request.Method.Equals("GET"))
        //    {

        //        newSpieler = new Spieler()
        //        {
        //            vorname = Request.Query["Vorname"],
        //            email = Request.Query["Email"],
        //            jahrgang = Request.Query["Jahrgang"],
        //            nachname = Request.Query["Nachname"],
        //            telefon = Request.Query["Telefon"]
        //        };
        //    }

        //    else if (Request.Method.Equals("POST"))
        //    {
        //        newSpieler = new Spieler()
        //        {
        //            vorname = Request.Form["Vorname"],
        //            email = Request.Form["Email"],
        //            jahrgang = Request.Form["Jahrgang"],
        //            nachname = Request.Form["Nachname"],
        //            telefon = Request.Form["Telefon"]
        //        };
        //    }

        //    SpielerRepo.SpielerListe.Add(newSpieler);

        //    return View("SeeSpieler", newSpieler);
        //}

        //Folie 4-23 (Explizites Model-Binding > doch es geht noch einfacher
        // *************************************************************************************
        //public ActionResult SeeSpieler2()
        //{
        //    Spieler newSpieler = new Spieler();
        //    try
        //    {
        //        if (TryUpdateModelAsync(newSpieler).Result)
        //        {
        //        } 
        //    }
        //    catch (Exception e)
        //    {
        //                Console.WriteLine(e);
        //                throw;
        //    }

        //    SpielerRepo.SpielerListe.Add(newSpieler);

        //    return View("SeeSpieler", newSpieler);
        //}

        //Folie 4-24 (Implizites Model-Binding > sehr schlanke, elegante Art
        // *************************************************************************************

        public ActionResult SeeSpieler2(Spieler spieler)
        {
            SpielerRepo.SpielerListe.Add(spieler);
            return View("SeeSpieler", spieler);
        }
    }
}

Aufgabe1_Registrierung/Controllers/SpielerListeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aufgabe1_Registrierung.Data;
using Aufgabe1_Registrierung.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Aufgabe1_Registrierung.Controllers
{
    public class SpielerListeController : Controller
    {

        public IActionResult SeeList()
        {
            return View(SpielerRepo.SpielerListe);
        }

        public ActionResult Search(string search)
        {
            ViewBag.Spielerliste = new SelectList(SpielerRepo.SpielerListe, "vorname", "nachname");
            //var spieler = SpielerRepo.SpielerListe.Where(a => a.vorname.StartsWith(begriff)).Take(10);
            return View(SpielerRepo.SpielerListe.Where(a=>a.vorname.StartsWith(search)).ToList());
        }
    }
}

Aufgabe1_Registrierung/Views/Home/Startseite.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Start-Seite";
}

<!DOCTYPE html>


<H1> Startseite</H1>
@*<a href="/Registrierung/LoadFormular"> Registrierungs-Seite</a>*@

Aufgabe1_Registrierung/Views/Registrierung/LoadFormular.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Registrierung";
}

<!DOCTYPE html>


    <H1> Formular</H1>
    <form action="/SpielerDetail/SeeSpieler2" method="post">
        Vorname:<br>
        <input type="text" name="Vorname" value="">
        <br>
        Nachname:<br>
        <input type="text" name="Nachname" value="">
        <br>
        Telefon:<br>
        <input type="text" name="Telefon" value="">
        <br>
        Email:<br>
        <input type="text" name="Email" value="">
        <br>
        Jahrgang:<br>
        <input type="text" name="Jahrgang" value="">
        <br>
        <br>
        <input type="submit" value="SaveAndSeeDetail">
        <br>
    </form>
    @*<a href="/Home/Startseite"> Startseite</a>*@

Aufgabe1_Registrierung/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<environment names="Development">
    <link href="~/font-awesome/css/fontawesome.css" rel="stylesheet" />
    <link href="~/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</environment>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <table border="1" style="width:1200px">
        <tr>
            <td colspan="2" style="width:300px">
                <nav class="navbar navbar-expand-sm bg-light justify-content-center">
                    <ul class="nav">
                        <li class="nav">@Html.ActionLink("Startseite", "Startseite", "Home",null, new { @class = "nav-link" })</li>
                        <li class="nav">@Html.ActionLink("Registrierung", "LoadFormular", "Registrierung", null, new { @class = "nav-link" })</li>
                        <li class="nav">@Html.ActionLink("Details", "SeeSpieler", "SpielerDetail", null, new { @class = "nav-link" })</li>
                        <li class="nav">@Html.ActionLink("Spieler-Liste", "SeeList", "SpielerListe", null, new { @class = "nav-link" })</li>

                    </ul>
                </nav>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <h3>Spiel - Portal</h3>
            </td>
        </tr>

        <tr>
            <td style="height:450px" >@RenderBody()</td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <h4>©2019 Reto Abderhalden</h4>
            </td>
        </tr>
    </table>
</body>
</html>

Aufgabe1_Registrierung/Views/SpielerDetail/SeeSpieler.cshtml
@model Aufgabe1_Registrierung.Models.Spieler

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Details";
}

<!DOCTYPE html>


    <H1>Vielen Dank!</H1>
    <br>
    <H2>Spiel-Information:</H2>
    <br />
    <p>Blaa, blaa,blaa..</p>
    <br />
    <H1>Spielerdetails..</H1>

    <p>Vorname:</p>
    @Model.vorname
    <br>
    <p>Nachname:</p>
    @Model.nachname
    <br>
    @*<ul>
            @foreach (var spieler in Model)
            {
                <li>@spieler.vorname @spieler.nachname @spieler.email</li>
            }
        </ul>*@

    @*<p>Name: @ViewBag.Nachname</p>
        <p>Vorname: @ViewBag.Vorname</p>
        <p>Mobile: @ViewBag.Telefon</p>
        <p>Email: @ViewBag.Email</p>
        <p>Jahrgang: @ViewBag.Jahrgang</p>*@


    @*<a href="/Home/Startseite">Startseite</a>
    <br />
    <a href="/Registrierung/LoadFormular">Nächster Spieler erfassen</a>
    <br />
    <a href="/SpielerListe/SeeList">Spieler-Übersicht</a>*@

Aufgabe1_Registrierung/Views/SpielerListe/Search.cshtml
@model IEnumerable<Aufgabe1_Registrierung.Models.Spieler>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Suche";
}

<!DOCTYPE html>

<H1>Gefundene Spieler:</H1>

<table>
    <tr>
        <th>Vorname:</th>
        <th>Nachname:</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.vorname </td>
            <td>@item.nachname</td>
        </tr>
    }
</table>
<br />
<br />
@Html.DropDownList("Spielerliste","Wähle Spieler")

Aufgabe1_Registrierung/Views/SpielerListe/SeeList.cshtml
@model IEnumerable<Aufgabe1_Registrierung.Models.Spieler>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Spieler-Liste";
}

<!DOCTYPE html>

    <H2>Spieler-Übersicht:</H2>

    <table>
        <tr>
            <th>Vorname:</th>
            <th>Nachname:</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.vorname </td>
                <td>@item.nachname</td>
            </tr>
        }

    </table>
    <br />
    <h2>Suche Spieler:</h2>
<p>
    @using (Html.BeginForm("Search","SpielerListe",FormMethod.Get))
    {
        <b>Suche:</b>
        @Html.TextBox("search")<input type="submit" value="Search"/>
    }
</p>

    @*<a href="/Home/Startseite">zur Startseite</a>*@